export default {
  events: [
  {
    'title': 'Mmmmmmmmmmmmmmmmmm',
    'isRecurrence': true,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emmaaaaaaaaa Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 PM - 10:30 PM',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '4000',
    'soapNoteTitle': 'View Soap Note',
    'setProfileTitle': 'setProfileTitleAccessor',
    'staffs': [{
        'staffName': 'Morgan',
        'image': '../src/img/doctor.png',
        'link': ''
      },
      {
        'staffName': 'Jason',
        'image': '../src/img/doctor.png',
        'link': ''
      },
      {
        'staffName': 'Charlee',
        'image': '../src/img/doctor.png',
        'link': ''
      }
    ],
    'resourceId': 'sched01',
    'start': new Date(2018, 5, 27, 20, 0, 0, 0),
    'end': new Date(2018, 5, 27, 21, 0, 0, 0),
    'isRecurrenceEdit': false,
    'isEdit': true,
    'isDelete': true,
    'isDragable': true,
  }, {
    'title': 'Bbbbbbbbbbbbbb',
    'isRecurrence': true,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 10:30',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    'soapNoteTitle': 'Create Soap Note',
    'resourceId': 'sched01',
    'start': new Date(2018, 5, 27, 5, 30, 0, 0),
    'end': new Date(2018, 5, 27, 6, 30, 0, 0),
    'isRecurrenceEdit': false,
    'isEdit': false,
    'isDelete': true,
    'isCancel': false,
    'isAppointmentRendered': true,
    'isVideoCall': true,
    'isAppoinmentCancelled': true,
    'practitionerName': 'Bbbb singh',
    'isUnCancel': true,
    'cancellationReason': 'not defined',
    'isDragable': true,
  }, {
    'title': 'Aaaaaaaaa',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    'soapNoteTitle': 'View Soap Note',
    'resourceId': 'sched01',
    'start': new Date(2018, 5, 27, 6, 0, 0, 0),
    'end': new Date(2018, 5, 27, 6, 30, 0, 0),
    'isRecurrenceEdit': false,
    'isEdit': true,
    'isDelete': true,
    'isCancel': false,
    'isAppointmentRendered': true,
    'isVideoCall': true,
    'isAppoinmentCancelled': true,
    'practitionerName': 'Aaaa singh',
    'isUnCancel': true,
    'cancellationReason': 'Text is available under the Creative Commons Attribution-ShareAlike License; additional terms may apply. By using this site, you agree to the Terms of Use and Privacy Policy',
    'isDragable': false,
  }, {
    'title': 'Ccccccccccccc',
    'isRecurrence': true,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    soapNoteTitle: 'View Soap Note',
    'resourceId': 'sched01',
    'start': new Date(2018, 5, 27, 6, 0, 0, 0),
    'end': new Date(2018, 5, 27, 7, 30, 0, 0),
    'isDragable': false,
  }, {
    'title': 'Smartdata Events',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    'soapNoteTitle': 'Create Soap Note',
    'resourceId': 'sched01',
    'start': new Date(2018, 5, 27, 5, 30, 0, 0),
    'end': new Date(2018, 5, 27, 10, 30, 0, 0),
    'isDragable': false,
  }, {
    'title': 'Another Meeting',
    'isRecurrence': true,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    'soapNoteTitle': 'Soap Note',
    'resourceId': 'sched01',
    'statusId':1,
    'start': new Date(2018, 5, 27, 2, 30, 0, 0),
    'end': new Date(2018, 5, 27, 4, 30, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting 1',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 PM - 8:30 PM',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    'resourceId': 'sched02',
    'statusId':1,
    'start': new Date(2018, 5, 27, 4, 0, 0, 0),
    'end': new Date(2018, 5, 27, 4, 15, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting 2',
    'isRecurrence': true,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 PM - 8:30 PM',
    'appointmentAddress': 'ROOM NO 228-230, FIRST FLOOR, DISTRICT ADMINISTRATIVE COMPLEX, SECTOR 76, Sahibzada Ajit Singh Nagar, Chandigarh, 160055',
    'coPay': '',
    'resourceId': 'sched02',
    'start': new Date(2018, 5, 27, 4, 0, 0, 0),
    'end': new Date(2018, 5, 27, 4, 15, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting 3',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'coPay': '',
    'resourceId': 'c',
    'start': new Date(2018, 5, 27, 4, 0, 0, 0),
    'end': new Date(2018, 5, 27, 4, 15, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting 4',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'coPay': '',
    'resourceId': 'sched03',
    'start': new Date(2018, 5, 27, 3, 45, 0, 0),
    'end': new Date(2018, 5, 27, 4, 15, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting 5',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'coPay': '',
    'resourceId': 'sched03',
    'start': new Date(2018, 5, 27, 2, 10, 0, 0),
    'end': new Date(2018, 5, 27, 6, 30, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting 6',
    'isRecurrence': false,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'coPay': '',
    'resourceId': 'sched02',
    'start': new Date(2018, 5, 27, 1, 50, 0, 0),
    'end': new Date(2018, 5, 27, 5, 0, 0, 0),
    'isDragable': false,
  },
  {
    'title': 'Another Meeting',
    'isRecurrence': true,
    'patientName': 'SSSSSSSSSSSSS',
    'clinicianImage': '../src/img/doctor.png',
    'clinicianName': 'Dr Emma Anderson',
    'appointmentType': 'Regular appointment',
    'appointmentTime': '8:00 - 8:30',
    'coPay': '',
    'resourceId': 'sched02',
    'statusId':1,
    'start': new Date(2018, 5, 27, 2, 30, 0, 0),
    'end': new Date(2018, 5, 27, 4, 30, 0, 0),
    'isDragable': false,
  }
  ],

  list: [{
    id: 'sched01',
    title: 'sched01'
  }, {
    id: 'sched02',
    title: 'sched02'
  }, {
    id: 'sched03',
    title: 'sched03'
  }]
}
