export const SCHEDULE_ACTIONS = {
    GET_DRIVE_TIME: 'GET_DRIVE_TIME',
    POPULATE_DATABASE_APPOINTMENTS_FROM_THIRDPARTY_API: 'POPULATE_DATABASE_APPOINTMENTS_FROM_THIRDPARTY_API',
    SET_APPOINTMENTS_FROM_DATABASE: 'SET_APPOINTMENTS_FROM_DATABASE',
    SET_CURRENT_DRIVE_TIME: 'SET_CURRENT_DRIVE_TIME'
  };
