export const SCHEDULE_ACTIONS = {
    GET_DRIVE_DATA: 'GET_DRIVE_DATA',
    GET_APPOINTMENTS_FROM_THIRDPARTY_API: 'GET_APPOINTMENTS_FROM_THIRDPARTY_API',
    PUT_APPOINTMENT_TO_DATABASE: 'PUT_APPOINTMENT_TO_DATABASE',
    PUT_APPOINTMENTS_TO_THIRDPARTY_API: 'PUT_APPOINTMENTS_TO_THIRDPARTY_API',
    SET_APPOINTMENTS_FROM_DATABASE: 'SET_APPOINTMENTS_FROM_DATABASE',
    SET_APPOINTMENTS_AFTER_DRAG_AND_DROP: 'SET_APPOINTMENTS_AFTER_DRAG_AND_DROP',
    SET_CURRENT_DATE: 'SET_CURRENT_DATE',
    SET_CURRENT_DRIVE_DATA: 'SET_CURRENT_DRIVE_DATA',
    SET_RESOURCES: 'SET_RESOURCES',
    UPDATE_CURRENT_DATE: 'UPDATE_CURRENT_DATE',
    UPDATE_MOVED_AND_BEFORE_MOVED: 'UPDATE_MOVED_AND_BEFORE_MOVED',
    UPDATE_EVENTS_UPON_MOVE: 'UPDATE_EVENTS_UPON_MOVE',
  };
