export const SCHEDULE_ACTIONS = {
    GET_DRIVE_TIME: 'GET_DRIVE_TIME',
    GET_APPOINTMENTS_FROM_THIRDPARTY_API: 'GET_APPOINTMENTS_FROM_THIRDPARTY_API',
    SET_APPOINTMENTS_FROM_DATABASE: 'SET_APPOINTMENTS_FROM_DATABASE',
    SET_APPOINTMENTS_AFTER_DRAG_AND_DROP: 'SET_APPOINTMENTS_AFTER_DRAG_AND_DROP',
    SET_CURRENT_DRIVE_TIME: 'SET_CURRENT_DRIVE_TIME',
    SET_RESOURCES: 'SET_RESOURCES'
  };
